djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviive/', include('reviive.urls', namespace='reviive')),
    path('reviveStoryList/', include('reviive.urls', namespace='reviveStoryList')),
    path('getIdeas/', include('reviive.urls', namespace='getIdeas')),
    path('findProf/', include('reviive.urls', namespace='findProf')),
    path('budgetEstimation/', include('reviive.urls', namespace='budgetEstimation')),
    path('findProf/customerReview/', include('reviive.urls', namespace='customerReview')),
    path('messageBox/', include('reviive.urls', namespace='messageBox')),
    path('renovationPriceGuide/', include('reviive.urls', namespace='renovationPriceGuide')),
    path('contractors/', include('reviive.urls', namespace='contractors')),
    path('users/', include('users.urls', namespace='users')),
]

reviive/urls.py
from django.urls import path
from . import views

app_name = 'reviive'
urlpatterns = [
    # reviive_story views
    path('', views.reviive_list, name='reviive_list'),
    path('reviveStoryList', views.reviive_story_list, name='reviive_story_list'),
    path('getIdeas/', views.getIdeas, name='getIdeas'),
    path('findProf/', views.findProf, name='findProf'),
    path('budgetEstimation/', views.budgetEstimation, name='budgetEstimation'),
    path('findProf/customerReview/', views.customerReview, name='customerReview'),
    path('messageBox/', views.messageBox, name='messageBox'),
    path('renovationPriceGuide/', views.renovationPriceGuide, name='renovationPriceGuide'),
    path('contractors/', views.contractors, name='contractors'),
    path('reviveStoryList/edit/<int:renovation_id>/', views.edit_renovation, name='edit_renovation'),
    path('reviveStoryList/delete/<int:renovation_id>/', views.delete_renovation, name='delete_renovation'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # reviive_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('manage_users/', views.user_management, name='manage_users'),
    path('change_user_role/', views.change_user_role, name='change_user_role'),

]

reviive/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class RenovationPrice(models.Model):
    item = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    name = models.CharField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('reviive:renovationPriceGuide')

# class RenovationPrice:
#     def __init__(self, renovid, item, price):
#         self.renovid = renovid
#         self.item = item
#         self.price = price
#
# renovation1 = RenovationPrice(renovid="1001", item= "Paint (Behr)", price="$50 per gallon")
# renovation2 = RenovationPrice(renovid="1002", item= "Paint (Sherwin-Williams)", price="$40 to $70 per gallon")
# renovation3 = RenovationPrice(renovid="1003", item= "Paint (Dulux)", price="$30 to $60 per gallon")
# renovation4 = RenovationPrice(renovid="1004", item= "Tiles (Mohawk)", price="$1 to $5 per square foot")
# renovation5 = RenovationPrice(renovid="1005", item= "Tiles (Marazzi)", price="$2 to $7 per square foot")
# renovation6 = RenovationPrice(renovid="1006", item= "Tiles (Porcelanosa)", price="$10 per square foot")
# renovation7 = RenovationPrice(renovid="1007", item= "Mirror (IKEA)", price="$10 to $100")
# renovation8 = RenovationPrice(renovid="1008", item= "Mirror (Pottery)", price="$100")
# renovation9 = RenovationPrice(renovid="1009", item= "Mirror (Barn)", price="$100 to $300")
#
# renovations = [renovation1, renovation2, renovation5, renovation9, renovation3, renovation7, renovation4, renovation6, renovation8]

# renovations = []

regular_user = {"username": "samheeta", "password": "regular"}

reviive/forms.py
from django import forms
from .models import RenovationPrice



class RenovationForm(forms.ModelForm):
    class Meta:
        model = RenovationPrice
        fields = ['item', 'price', 'name']

reviive/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from actions.models import Action
from reviive.forms import RenovationForm
from reviive.models import RenovationPrice
from .models import regular_user

# Create your views here.


def reviive_list(request):
    return render(request, "reviive/reviive_story/login.html")


def reviive_story_list(request):
    # if request.session.get("username", False):
        actions = Action.objects.all().order_by('-created')

        return render(request,
                      "reviive/reviive_story/list.html",
                      {"actions": actions}
                      )


def getIdeas(request):
        return render(request,
                      "reviive/reviive_story/getIdeas.html")


def findProf(request):
    if request.session.get("username", False):

        actions = Action.objects.all().order_by('-created')

        return render(request,
                  "reviive/reviive_story/findProf.html",
        {"actions": actions}
                      )


def budgetEstimation(request):
    return render(request,
                  "reviive/reviive_story/budgetEstimation.html")


def customerReview(request):

        if request.method == 'POST':
            # process the form
            title = request.POST.get('add-title')
            price = request.POST.get('add-description')
            name = request.session['username']
            # name = request.POST.get('add-name')
            # User.objects.filter()
            # print(title, price, name)

            rp = RenovationPrice(
                item=title,
                price=price,
                name=name,
            )
            rp.save()

            # log the action
            action = Action(
                user=name,
                verb="review added by",
                # target_id=rp
            )
            action.save()

            messages.add_message(request, messages.SUCCESS, "You successfully added a review: %s" % rp.item)

            return redirect("reviive:renovationPriceGuide")
        else:
            #show the form
            return render(request,
                  "reviive/reviive_story/customerReview.html")


def messageBox(request):
    return render(request,
                  "reviive/reviive_story/messageBox.html")


def edit_renovation(request, renovation_id):
    print(renovation_id)
    renovation = get_object_or_404(RenovationPrice, id=renovation_id)
    if request.method == 'POST':
        form = RenovationForm(request.POST, instance=renovation)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, "Review Successfully Edited")
            return redirect('reviive:renovationPriceGuide')  # Redirect to the list view or any other appropriate view
    else:
        form = RenovationForm(instance=renovation)

    return render(request, 'reviive/reviive_story/edit_renovation.html', {'form': form})


def delete_renovation(request, renovation_id):
    renovation = get_object_or_404(RenovationPrice, id=renovation_id)
    if request.method == 'POST':  # Confirm deletion
        renovation.delete()
        messages.add_message(request, messages.WARNING, "Review Successfully Deleted")
        return redirect('reviive:renovationPriceGuide')  # Redirect to the list view or any other appropriate view
    return render(request, 'reviive/reviive_story/confirm_delete.html', {'renovation': renovation})



def contractors(request):
    return render(request,
                  "reviive/reviive_story/contractors.html",
                  )


def renovationPriceGuide(request):
        renovations = RenovationPrice.objects.all()
        context = {"renovations": renovations
                   }
        return render(request,
                      "reviive/reviive_story/renovationPriceGuide.html",
                      context
                      )

# def login(request):
#     username = request.POST.get("username")
#     pw = request.POST.get("pw")
#     if(username == regular_user['username']) and (pw == regular_user['password']):
#         request.session['username'] = username
#         request.session['role'] = 'regular'
#         return redirect('reviive:reviive_story_list')
#     else:
#         return redirect('reviive:reviive_story_list')
#
# def logout(request):
#     del request.session['username']
#     del request.session['role']
#     return redirect('reviive:reviive_story_list')

templates/reviive/reviive_story/budgetEstimation.html
{% extends "reviive/base.html" %}

{% load static %}

{#{% block page-title %}Budget Estimation Calculator{% endblock %}#}

{% block main %}
<div>
    <!-- Budget Estimation Calculator Section -->
    <div id="calculatorContainer" >
        <h1>Budget Estimation Calculator</h1>
        <!-- Input fields for item and cost -->
        <label for="item">Item:</label>
        <input type="text" id="item" placeholder="Enter item name">
        <label for="cost">Cost:</label>
        <input type="number" id="cost" placeholder="Enter cost">
         <!-- Button to add an expense -->
        <button id="addExpense">Add Expense</button>
        <!-- List of expenses will be displayed here -->
        <ul id="expenseList">
            <!-- Expenses will be listed here -->
        </ul>
        <!-- Total Expenses -->
        <p>Total Expenses: $<span id="totalExpenses">0.00</span></p>
    </div>
</div>
{% endblock %}

{% block css %}{% static "css/budget.css" %}{% endblock %}

<script src="{% static 'js/budgetEstimation.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

templates/reviive/reviive_story/confirm_delete.html
{% extends "reviive/base.html" %}

{% load static %}
{#{% load humanize %}#}


{% block page-title %}Contrators{% endblock %}
{#<link rel="icon" href="{% static 'reviive/base.html' %}" type="image/x-icon">#}
{% block main %}
    <div class = "delete-main" >
  <h2>Are you sure you want to delete this review?</h2>
  <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'reviive:renovationPriceGuide' %}" class="btn btn-secondary">Cancel</a>
  </form>
    </div>
{% endblock %}
{% block css %}{% static "css/confirm_delete.css" %}{% endblock %}
{#<script src="{% static 'js/customerReview.js' %}"></script>#}
{#<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}

templates/reviive/reviive_story/contractors.html
{% extends "reviive/base.html" %}

{% load static %}
{#{% load humanize %}#}


{% block page-title %}Contrators{% endblock %}
<link rel="icon" href="{% static 'reviive/base.html' %}" type="image/x-icon">
{% block main %}

    <div id = news>
        <h2 id ="section-heading">Find Professionals</h2>
        <div class="news-story">
            <h3 class="news-title"><a href="samheeta.g@gmail.com">samheeta</a></h3>
            <p class="news-description">hiehello</p>

            <p class="news-byline">Submitted by <a href="#">hello world</a> 44/55/200 <a href="{% url 'reviive:renovationPriceGuide' %}" class="comments">view 30 comments</a></p>
            <div class="news-pts">
                <button class="upvote">+</button>
                <div class="score">150</div>
                 <button class="downvote">-</button>
                <a href="{% url 'reviive:customerReview' %}" class="categorys_btn">Give your feedback</a>
            </div>
        </div>
    </div>

{% endblock %}

{% block css %}{% static "css/contractors.css" %}{% endblock %}
<script src="{% static 'js/contractors.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script defer src="{% static 'js/contractors.js' %}"></script>

templates/reviive/reviive_story/customerReview.html
{% extends "reviive/base.html" %}

{% load static %}

{% block page-title %}Budget Estimation Calculator{% endblock %}

{% block main %}
    <div>

    <div class="contractor-profile">

        <form id="ad-news-story" action=" " method="post">
            <h1>Service Feedback</h1><br>

            <label for="add-title">Company Name</label>
            <input id="add-title" name="add-title" type="text" required><br>
            <br>

            <label for="add-description">Customer Review</label>
            <input id="add-description" name="add-description" type="text" required>

            <input type="submit" name="submit" value="Submit Review">
            {% csrf_token%}
        </form>
    </div>
    </div>

{% endblock %}

{% block css %}{% static "css/customerReview.css" %}{% endblock %}
<script src="{% static 'js/customerReview.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

templates/reviive/reviive_story/edit_renovation.html
{% extends "reviive/base.html" %}

{% load static %}
{#{% load humanize %}#}


{% block page-title %}Contrators{% endblock %}
{#<link rel="icon" href="{% static 'reviive/base.html' %}" type="image/x-icon">#}
{% block main %}
 <div class="edit-main">
  <h2>EDIT REVIEW</h2>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Save changes</button>
  </form>
    </div>

{% endblock %}
{% block css %}{% static "css/edit_renovation.css" %}{% endblock %}
{#<script src="{% static 'js/customerReview.js' %}"></script>#}
{#<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}

templates/reviive/reviive_story/findProf.html
{% extends "reviive/base.html" %}
{% load static %}

{% block page-title %}findProf{% endblock %}

{% block main %}
     <div class="categorys">

            <div class="categorys_box">

                <div class="categorys_card">
                    <div class="categorys_image">
                        <img src="{% static 'img/17.jpg' %}">
                    </div><br>
                    <div class="categorys_tag">
                        <h3>Amendis interior design</h3>
                        <p>Interior Designer & Raumausstatter | Hamburg</p>
                        <h3>services provided</h3>
                        <p>Kitchen Remodeling, Bathroom Remodeling, Interior Painting, Exterior Painting,
                            Carpentry and Woodwork, Flooring Installation, Electrical Work, Plumbing Services,</p><br>
                        <a href="{% url 'reviive:customerReview' %}" class="categorys_btn">Feedback</a>
                        <a href="{% url 'reviive:messageBox' %}"  class="categorys_btn">Send Message</a>
                    </div>
                </div>

                <div class="categorys_card">
                    <div class="categorys_image">
                        <img src="{% static 'img/2.jpg' %}">
                    </div><br>
                    <div class="categorys_tag">
                        <h3>Forma Design</h3>
                        <p>Interior Designer & Raumausstatter | Hamburg</p>
                        <h3>services provided</h3>
                        <p>Kitchen Remodeling, Bathroom Remodeling, Interior Painting, Exterior Painting,
                            Carpentry and Woodwork, Flooring Installation, Electrical Work, Plumbing Services,</p><br>
                            <a href="{% url 'reviive:customerReview' %}" class="categorys_btn">Feedback</a>
                            <a href="{% url 'reviive:messageBox' %}"  class="categorys_btn">Send Message</a>
                    </div>
                </div>

                <div class="categorys_card">
                    <div class="categorys_image">
                        <img src="{% static 'img/9.jpg' %}">
                    </div><br>
                    <div class="categorys_tag">
                        <h3>Carnemark design</h3>
                        <p>Interior Designer & Raumausstatter | Hamburg</p>
                        <h3>services provided</h3>
                        <p>Kitchen Remodeling, Bathroom Remodeling, Interior Painting, Exterior Painting,
                            Carpentry and Woodwork, Flooring Installation, Electrical Work, Plumbing Services,</p><br>
                            <a href="{% url 'reviive:customerReview' %}" class="categorys_btn">Feedback</a>
                            <a href="{% url 'reviive:messageBox' %}"  class="categorys_btn">Send Message</a>
                    </div>
                </div>
            </div>
        </div>


            <!-- Main content section -->
    <div class="main">
        <!-- Categories section -->
         <div class="categors">
             <!-- Add content for categories if needed -->
             </div>

             <!-- Categories card -->
             <div class="categories_card">
{#                    <h2>Find Professionals</h2>#}
{#                    <a href="">Interir Designers</a>#}
{#                    <a href="">Building Designers</a>#}
{#                    <!-- <a class="tab">Architects & Building Designers</a> -->#}
{#                    <a href="">Design-Build Firms</a>#}
{#                    <a href="">Bathroom Designers</a>#}
{#                    <a href="">General Contractors</a>#}
{#                    <a href="">Home Builders</a>#}
{#                    <a href="">Roofing & Gutters</a>#}
{#                    <a href="">Kitchen Remodelers</a>#}
{#                    <a href="">Tile & Stone</a>#}
                 {% include "actions/action/feed.html" %}
                </div>
     </div>

{% endblock %}

{% block css %}{% static "css/findProf.css" %}{% endblock %}

templates/reviive/reviive_story/getIdeas.html
{% extends "reviive/base.html" %}
{% load static %}

{% block page-title %}getIdeas{% endblock %}

{% block main %}
    <div class="categories_card">
         <h2>Get Ideas</h2>
         <a href="">Kitchen</a>
         <a class="tab">Living</a>
         <a href="">Bedroom</a>
         <a href="GetIdeas.html">Living</a>
         <a href="">Dining</a>
         <a href="">Outdoor</a>
         <a href="">Baby & Kids</a>
         <a href="">Home Office</a>
         <a href="">Exterior</a>
         <a href="">Storage & Closet</a>
    </div>


 <div class="categorys">

    <div class="categorys_box">

        <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/2.jpg' %}">

            </div>
            <div class="categorys_tag">

            </div>
        </div>

          <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/2.jpg' %}">
            </div>

        </div>


         <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/6.jpg' %}">
            </div>

        </div>

         <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/7.png' %}">
            </div>

        </div>

        <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/13.jpg' %}">
            </div>

        </div>

         <div class="categorys_card">
            <div class="categorys_image">
                <img src="{% static 'img/9.jpg' %}">
            </div>

        </div>

    </div>
  </div>

{% endblock %}

{% block css %}{% static "css/getIdeas.css" %}{% endblock %}

templates/reviive/reviive_story/list.html
{% extends "reviive/base.html" %}

{% load static %}

{% block page-title %}Home Page{% endblock %}

{% block main %}

{% if request.session.username %}


    <div class="feed">
    <div class="categories_card">
        {% include "actions/action/feed.html" %}
    </div>
    </div>
{% endif %}
    <div class="main-tag">
            <!-- Main content and welcome message -->
            <p>
                "Welcome to REVIIVE, your ultimate companion for all your home renovation and improvement projects.
                With our user-friendly and feature-packed app, you can turn your renovation ideas into reality.
                Whether you're looking to update a single room or embark on a full-scale home makeover, we've got you covered.
                Explore a world of inspiration, browse a vast library of design ideas, manage your projects with ease, and connect
                with skilled professionals—all at your fingertips. Start your journey toward a more beautiful and functional living
                space today with REVIIVE."
            </p>
            <!-- Button to get started -->
            <a href="#" class="main-btn">GET STARTED</a>
    </div>

        <!-- Image hover section -->
        <div class="main">
            <div class="main_img">
                <!-- First image with an ID -->
                <img id="image1" src="{% static "img/image1.jpg" %}" alt="Image 1">
            </div>
            <div class="main_img2">
                <!-- Second image with an ID -->
                <img id="image2" src="{% static "img/image2.jpg" %}" alt="Image 2">
            </div>
        </div>

{% endblock %}


{% block css %}{% static "css/HomeUI.css" %}{% endblock %}

templates/reviive/reviive_story/messageBox.html
{% extends "reviive/base.html" %}

{% load static %}

{% block page-title %}messageBox{% endblock %}

{% block main %}
    <div class="frem">
    <div class="logo-name">

        <p>WHAT DO YOU WANT TO SHARE</p>
    </div>
    <div class="text-area" contenteditable data-placeholder="Write here"></div>
    <div class="bottom-cont">
        <a href="#">ADD PHOTO</a>
        <a href="#">SEND</a>

    </div>
    </div>
{% endblock %}

{% block css %}{% static "css/messageBox.css" %}{% endblock %}

templates/reviive/reviive_story/renovationPriceGuide.html
{% extends "reviive/base.html" %}
{% load static %}

{% block main %}

<div class="search-container">
 <h2>CUSTOMER FEED BACK</h2>

        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}

    <div class="search-bar">
        <input type="text" id="myInput" placeholder="Search here..">
        <button onclick="searchTable()" class="search-button">Search</button>

    </div>
        <table id="myTable">
            <tr>
                <th>COMPANY NAME</th>
                <th>REVIEWS</th>
                <th>NAME</th>
                <th>EDIT/DELETE</th>
            </tr>
            {% for renovation in renovations %}
                <tr>
                    <td>{{ renovation.item }}</td>
                    <td>{{ renovation.price }}</td>
                    <td>{{ renovation.name }}</td>
                    {% if request.user.is_superuser or renovation.name == request.user.username %}

                    <td>
                        <a href="{% url 'reviive:edit_renovation' renovation.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'reviive:delete_renovation' renovation.id %}" class="btn btn-danger">Delete</a>
                    </td>
                    {% endif %}

                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

{% block css %}{% static "css/renovationPriceGuide.css" %}{% endblock %}
<script src="{% static 'js/renovationPriceGuide.js' %}"></script>