djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviive/', include('reviive.urls', namespace='reviive')),
    path('reviveStoryList/', include('reviive.urls', namespace='reviveStoryList')),
    path('getIdeas/', include('reviive.urls', namespace='getIdeas')),
    path('findProf/', include('reviive.urls', namespace='findProf')),
    path('budgetEstimation/', include('reviive.urls', namespace='budgetEstimation')),
    path('findProf/customerReview/', include('reviive.urls', namespace='customerReview')),
    path('messageBox/', include('reviive.urls', namespace='messageBox')),
    path('renovationPriceGuide/', include('reviive.urls', namespace='renovationPriceGuide')),
    path('contractors/', include('reviive.urls', namespace='contractors')),
    path('users/', include('users.urls', namespace='users')),
]

reviive/urls.py
from django.urls import path
from . import views

app_name = 'reviive'
urlpatterns = [
    # reviive_story views
    path('', views.reviive_list, name='reviive_list'),
    path('reviveStoryList', views.reviive_story_list, name='reviive_story_list'),
    path('getIdeas/', views.getIdeas, name='getIdeas'),
    path('findProf/', views.findProf, name='findProf'),
    path('budgetEstimation/', views.budgetEstimation, name='budgetEstimation'),
    path('findProf/customerReview/', views.customerReview, name='customerReview'),
    path('messageBox/', views.messageBox, name='messageBox'),
    path('renovationPriceGuide/', views.renovationPriceGuide, name='renovationPriceGuide'),
    path('contractors/', views.contractors, name='contractors'),
    path('reviveStoryList/edit/<int:renovation_id>/', views.edit_renovation, name='edit_renovation'),
    path('reviveStoryList/delete/<int:renovation_id>/', views.delete_renovation, name='delete_renovation'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # reviive_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('manage_users/', views.user_management, name='manage_users'),
    path('change_user_role/', views.change_user_role, name='change_user_role'),

]

reviive/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class RenovationPrice(models.Model):
    item = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    name = models.CharField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('reviive:renovationPriceGuide')

# class RenovationPrice:
#     def __init__(self, renovid, item, price):
#         self.renovid = renovid
#         self.item = item
#         self.price = price
#
# renovation1 = RenovationPrice(renovid="1001", item= "Paint (Behr)", price="$50 per gallon")
# renovation2 = RenovationPrice(renovid="1002", item= "Paint (Sherwin-Williams)", price="$40 to $70 per gallon")
# renovation3 = RenovationPrice(renovid="1003", item= "Paint (Dulux)", price="$30 to $60 per gallon")
# renovation4 = RenovationPrice(renovid="1004", item= "Tiles (Mohawk)", price="$1 to $5 per square foot")
# renovation5 = RenovationPrice(renovid="1005", item= "Tiles (Marazzi)", price="$2 to $7 per square foot")
# renovation6 = RenovationPrice(renovid="1006", item= "Tiles (Porcelanosa)", price="$10 per square foot")
# renovation7 = RenovationPrice(renovid="1007", item= "Mirror (IKEA)", price="$10 to $100")
# renovation8 = RenovationPrice(renovid="1008", item= "Mirror (Pottery)", price="$100")
# renovation9 = RenovationPrice(renovid="1009", item= "Mirror (Barn)", price="$100 to $300")
#
# renovations = [renovation1, renovation2, renovation5, renovation9, renovation3, renovation7, renovation4, renovation6, renovation8]

# renovations = []

regular_user = {"username": "samheeta", "password": "regular"}

reviive/forms.py
from django import forms
from .models import RenovationPrice



class RenovationForm(forms.ModelForm):
    class Meta:
        model = RenovationPrice
        fields = ['item', 'price', 'name']

reviive/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from actions.models import Action
from reviive.forms import RenovationForm
from reviive.models import RenovationPrice
from .models import regular_user

# Create your views here.


def reviive_list(request):
    return render(request, "reviive/reviive_story/login.html")


def reviive_story_list(request):
    # if request.session.get("username", False):
        actions = Action.objects.all().order_by('-created')

        return render(request,
                      "reviive/reviive_story/list.html",
                      {"actions": actions}
                      )


def getIdeas(request):
        return render(request,
                      "reviive/reviive_story/getIdeas.html")


def findProf(request):
    if request.session.get("username", False):

        actions = Action.objects.all().order_by('-created')

        return render(request,
                  "reviive/reviive_story/findProf.html",
        {"actions": actions}
                      )


def budgetEstimation(request):
    return render(request,
                  "reviive/reviive_story/budgetEstimation.html")


def customerReview(request):

        if request.method == 'POST':
            # process the form
            title = request.POST.get('add-title')
            price = request.POST.get('add-description')
            name = request.session['username']
            # name = request.POST.get('add-name')
            # User.objects.filter()
            # print(title, price, name)

            rp = RenovationPrice(
                item=title,
                price=price,
                name=name,
            )
            rp.save()

            # log the action
            action = Action(
                user=name,
                verb="review added by",
                # target_id=rp
            )
            action.save()

            messages.add_message(request, messages.SUCCESS, "You successfully added a review: %s" % rp.item)

            return redirect("reviive:renovationPriceGuide")
        else:
            #show the form
            return render(request,
                  "reviive/reviive_story/customerReview.html")


def messageBox(request):
    return render(request,
                  "reviive/reviive_story/messageBox.html")


def edit_renovation(request, renovation_id):
    print(renovation_id)
    renovation = get_object_or_404(RenovationPrice, id=renovation_id)
    if request.method == 'POST':
        form = RenovationForm(request.POST, instance=renovation)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, "Review Successfully Edited")
            return redirect('reviive:renovationPriceGuide')  # Redirect to the list view or any other appropriate view
    else:
        form = RenovationForm(instance=renovation)

    return render(request, 'reviive/reviive_story/edit_renovation.html', {'form': form})


def delete_renovation(request, renovation_id):
    renovation = get_object_or_404(RenovationPrice, id=renovation_id)
    if request.method == 'POST':  # Confirm deletion
        renovation.delete()
        messages.add_message(request, messages.WARNING, "Review Successfully Deleted")
        return redirect('reviive:renovationPriceGuide')  # Redirect to the list view or any other appropriate view
    return render(request, 'reviive/reviive_story/confirm_delete.html', {'renovation': renovation})



def contractors(request):
    return render(request,
                  "reviive/reviive_story/contractors.html",
                  )


def renovationPriceGuide(request):
        renovations = RenovationPrice.objects.all()
        context = {"renovations": renovations
                   }
        return render(request,
                      "reviive/reviive_story/renovationPriceGuide.html",
                      context
                      )

# def login(request):
#     username = request.POST.get("username")
#     pw = request.POST.get("pw")
#     if(username == regular_user['username']) and (pw == regular_user['password']):
#         request.session['username'] = username
#         request.session['role'] = 'regular'
#         return redirect('reviive:reviive_story_list')
#     else:
#         return redirect('reviive:reviive_story_list')
#
# def logout(request):
#     del request.session['username']
#     del request.session['role']
#     return redirect('reviive:reviive_story_list')

templates/reviive/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


<!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include your JavaScript code -->
    <script src="{% static 'js/budgetEstimation.js' %}"></script>
    <script src="{% static 'js/customerReview.js' %}"></script>
    <script src="{% static 'js/renovationPriceGuide.js' %}"></script>

    <!-- Title for the webpage -->
    <title>Home page | {% block page-title %}{% endblock %}</title>
      <link rel="stylesheet" href ="{% block css %}{% endblock %}">
    <!-- Link to the external stylesheet for HomeUI -->
<link rel="icon" href="data:;base64,iVBORw0KGgo=">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/contractors.js' %}" defer></script>

    <!-- Link to the boxicons CSS library -->
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

    <!-- Import font-awesome icons -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
{#    <link rel="stylesheet" href="css/global.css">#}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body>

<section>
    <!-- Navigation menu -->
    <nav>
        <div class="logo">
            <!-- Logo image -->
            <img src="{% static "img/logo.png" alt=" " %}">
        </div>

        <!-- Navigation links with dropdowns -->
        <ul>
            {% if request.session.username %}
            <li><a href="{% url 'reviive:reviive_story_list' %}">HOME</a></li>
            <li><a href="{% url 'reviive:getIdeas' %}">GET IDEAS &#x25BE;</a>
                <ul class="dropdown">
                    <!-- Submenu items for getting ideas -->
                    <li><a href="{% url 'reviive:getIdeas' %}">Kitchen</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Bedroom</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Living</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Dining</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Outdoor</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Baby & Kids</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Home Office</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Exterior</a></li>
                    <li><a href="{% url 'reviive:getIdeas' %}">Storage & Closet</a></li>
                    <!-- ... Other submenu items ... -->
                </ul>
            </li>
            <li><a href="{% url 'reviive:findProf' %}">CONTRACTORS &#x25BE;</a>
                <ul class="dropdown">
                    <!-- Submenu items for finding professionals -->
                    <li><a href="{% url 'reviive:findProf' %}">Interior Designers & Decorators</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Architects & Building Designers</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Design-Build Firms</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Kitchen & Bathroom Designers</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Home Builders</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Roofing & Gutters</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Cabinets & Cabinetry</a></li>
                    <li><a href="{% url 'reviive:findProf' %}">Tile & Stone</a></li>

                    <!-- ... Other submenu items ... -->
                </ul>
            </li>
{#                <li><a href="{% url 'users:admin_edit_user' %}">PRICE POINT</a>#}
            <li><a href="{% url 'reviive:budgetEstimation' %}">PRICE POINT</a>
                <ul class="dropdown">
                    <!-- Submenu items for help -->
{#                    <li><a href="{% url 'reviive:contractors' %}">new contractor page</a></li>#}
{#                    <li><a href="{% url 'reviive:renovationPriceGuide' %}">Customer Feedback</a></li>#}
                </ul>
            </li>

             <li><a href="{% url 'reviive:renovationPriceGuide' %}">CUSTOMER FEEDBACK</a>

             <!-- Search form -->
{#            <form id="searchForm" action="search-results.html"   method="GET">#}
{#                <input type="text" name="query" placeholder="Enter your search phrase" required>#}
{#                <input type="submit" value="Search">#}
{#            </form>#}
            </li>

            <li>
                {% if request.user.is_superuser %}
                    <a href="{% url 'users:manage_users' %}">USER MANAGEMENT</a>
                {% endif %}
            </li>


              {% endif %}
        </ul>



       {% if request.session.username %}

         <form id ="login_box">
            <p>Logged in as <a href="{% url "users:profile" request.session.username %}"><strong>{{ request.session.username }}</strong></a>  | <a href="{% url 'users:logout' %}">Log out</a> </p>
        </form>

        {% else %}

        <form id ="login-box" action="{% url 'users:login' %}" method="POST">
            {%  csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="pw" placeholder="Password">
            <input type="submit" name="submit" value="Log in"> or <a href="{% url 'users:register' %}">Register</a>
        </form>

       {% endif %}

    {% if request.session.username %}
{#        <!-- Social icons -->#}
        <div class="social-icon">
{#            <i class='bx bxs-user'></i> <!-- User icon -->#}
{#             <form id="searchForm" action="search-results.html"   method="GET">#}
{#                <input type="text" name="query" placeholder="Enter your search phrase" required>#}
{#                <input type="submit" value="Search">#}
{#            </form>#}
        </div>
{#        <li><a href="{% url 'reviive:reviive_list' %}">logout</a>#}
{#        </li>#}
            {% endif %}

    </nav>

    <div class="main">

        {% block main %}{% endblock %}
    </div> <!-- main -->
</section>
<!-- Footer section -->
<footer>
    <div class="footer_main">
        <div class="tag">
            <!-- Footer links -->
            <a href="#">@Copyright2023,Reviive</a> |
            <a href="#Privacy Policy">Privacy Policy</a> |
            <a href="#About">About</a> |
            <a href="#Contact">Contact</a> |
        </div>

        <div class="tag">
            <!-- Social media icons -->
            <div class="social_link">
                <i class="fa-brands fa-facebook-f"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-linkedin-in"></i>
            </div>
        </div>
    </div>
</footer>
<script src="{% block script %}{% endblock %}"></script>

</body>
</html>