djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviive/', include('reviive.urls', namespace='reviive')),
    path('reviveStoryList/', include('reviive.urls', namespace='reviveStoryList')),
    path('getIdeas/', include('reviive.urls', namespace='getIdeas')),
    path('findProf/', include('reviive.urls', namespace='findProf')),
    path('budgetEstimation/', include('reviive.urls', namespace='budgetEstimation')),
    path('findProf/customerReview/', include('reviive.urls', namespace='customerReview')),
    path('messageBox/', include('reviive.urls', namespace='messageBox')),
    path('renovationPriceGuide/', include('reviive.urls', namespace='renovationPriceGuide')),
    path('contractors/', include('reviive.urls', namespace='contractors')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # reviive_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('manage_users/', views.user_management, name='manage_users'),
    path('change_user_role/', views.change_user_role, name='change_user_role'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

from actions.models import Action
from users.models import Details


def profile(request, username):
    user = get_object_or_404(User, username=username)
    actions = Action.objects.all().order_by('-created')

    if request.method == 'POST':
        # Get data from the form
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        # Update user object
        user.email = email
        user.first_name = first_name
        user.last_name = last_name


        # Save the updated user object
        user.save()

        # Redirect to the profile page or a success page
        return HttpResponseRedirect(reverse('users:profile', args=[username]))

    return render(request, "users/user/profile.html", {"user": user, "actions": actions})



# def profile(request, username):
#     user1 = get_object_or_404(User, username=username)
#     return render(request,
#                   "users/user/profile.html",
#                   {"user": user1}
#                   )


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        user = User.objects.create_user(username, email, password)

        # Set first_name and last_name
        user.first_name = first_name
        user.last_name = last_name

        # Save the user object with the updated fields
        user.save()

        messages.add_message(request, messages.SUCCESS,
                             "You successfully registered with the username: %s" % user.username)
        # messages.add_message(request, messages.SUCCESS, "Review Successfully Edited")
        return redirect('reviive:reviive_story_list')
    else:
        return render(request,
                      "users/user/register.html",
                      )




def login_user(request):
    request.session.flush()
    username = request.POST.get("username")
    pw = request.POST.get("pw")

    user = authenticate(username=username, password=pw)
    if user is not None:
        request.session['username'] = username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS,
                             "You have logged in successfully.")
        auth_login(request, user)
        return redirect('reviive:reviive_story_list')
    else:
        messages.add_message(request, messages.ERROR,
                             "Invalid username or password.")
    return render(request, 'reviive/reviive_story/list.html')


def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('reviive:reviive_story_list')

@user_passes_test(lambda u: u.is_superuser)
def change_user_role(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        new_role = request.POST.get('role')

        # Update user role
        print(new_role)
        user = User.objects.get(id=user_id)
        if new_role == 'admin':
            user.is_superuser = True
            user.is_staff = True  # Generally, superusers are also staff
        else:
            user.is_superuser = False
            user.is_staff = False
        user_details = Details.objects.get(user=user)
        user_details.role = new_role
        user_details.save()
        user.save()
        return redirect('users:manage_users')

    users = User.objects.all()
    return render(request, 'users/user/manage_users.html', {'users': users})


def user_management(request):
    all_users = User.objects.all()
    return render(request, 'users/user/manage_users.html', {'all_users': all_users})

templates/users/user/edit_profile.html
{% extends "reviive/base.html" %}

{% load static %}

{% block main %}
{% if request.user.is_superuser %}
    <form method="post" action="{% url 'users:profile' user.username %}">
        {% csrf_token %}
        <label for="first_name">First Name:</label>
        <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}">

        <label for="last_name">Last Name:</label>
        <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}">

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" value="{{ user.email }}">

        <input type="submit" value="Save Changes">
    </form>
{% endif %}

{% endblock %}

templates/users/user/manage_users.html
{% extends "reviive/base.html" %}
{% load static %}

{% block main %}
    <div class="head-title">
        <div class="left">
            <h1>User Role Management</h1>
        </div>
    </div>
    <div class="table-data">
        <div class="todo">
            <div class="container">
                {% if request.user.is_superuser %}
                    <div class="admin-role-management">
                        <table>
                            <tr>
                                <th>Username</th>
                                <th>Role</th>
                                <th>Change Role</th>
                                <th>Edit Profile</th>
                            </tr>
                            {% for user in all_users %}
                                <tr>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.details.role }}</td>
                                    <td class="table-cell">
                                        <form method="POST" action="{% url 'users:change_user_role' %}">
                                            {% csrf_token %}
                                            <select name="role" id="user-role">
                                                <option value="" disabled selected>change new role</option>
                                                <option value="admin">Admin User</option>
                                                <option value="regular">Registered User</option>
                                                <option value="unregistered">Unregistered User</option>
                                            </select>
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <button type="submit">role</button>
                                        </form>
                                    </td>
                                    <td class="no-wrap">
                                        <a href="{% url 'users:profile' user.username %}">Edit Profile</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% else %}
                    <p>You do not have permission to view this page.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            $('.container').on('click', '.delete-profile', function () {
                // Delete Profile button clicked
                const confirmation = confirm('Are you sure you want to delete your profile? This action cannot be undone.');
                if (confirmation) {
                    alert('Profile deleted successfully');
                    window.location.href = "{% url 'users:register' %}";
                }
            });

            $('.container').on('click', '.save-button', function () {
                // Save Changes button clicked
                alert('Profile has been updated');
                window.location.href = "{% url 'users:register' %}";
            });
        });
    </script>
{% endblock %}

{% block css %}{% static "css/manage_users.css" %}{% endblock %}

templates/users/user/profile.html
{% extends "reviive/base.html" %}

{% load static %}

{% block page-title %}Profile for {{ user.username }}{% endblock %}

{% block main %}

    <div class="feed">
    <div class="categories_card">
         {% include "actions/action/feed.html" %}
    </div>
    </div>


<div class="profile_info">

    <h2 id="section-heading">Profile for {{ user.username }}</h2>

    <dl>
        <dt>Username</dt>
        <dd>{{ user.username }}</dd>
        <dt>Email address</dt>
        <dd>{{ user.email }}</dd>
        <dt>Role</dt>
        <dd>{{ user.details.role }}</dd>
        <dt>First Name</dt>
        <dd>{{ user.first_name }}</dd>
        <dt>Last Name</dt>
        <dd>{{ user.last_name }}</dd>
    </dl>
    <br>
    <!-- Edit Details Button -->
    <button type="button" id="edit-button">Edit Details</button>
</div>



<div class="edit" style="display: none;" >

<form method="POST" action="{% url 'users:profile' user.username %}">
{#    <form method="post" action="{% url 'users:profile' username=user.username %}">#}


    <label for="username">Username</label>
    <input type="text" id="username" value="{{ user.username }}" disabled>

    <label for="email">Email address</label>
    <input type="email" name="email" id="email" value="{{ user.email }}">

    <label for="first_name">First name</label>
    <input type="text" name="first_name" id="first_name" value="{{ user.first_name }}">

    <label for="last_name">Last name</label>
    <input type="text" name="last_name" id="last_name" value="{{ user.last_name }}">


    {% csrf_token %}

    <input type="submit" value="Update Profile">
    </form>
</div>

<script>
    document.getElementById('edit-button').addEventListener('click', function() {
        var editDiv = document.querySelector('.edit');
        var infoDiv = document.querySelector('.profile_info');
        editDiv.style.display = 'block';
        infoDiv.style.display = 'none';
    });
</script>

{% endblock %}

{% block css %}{% static "css/profile.css" %}{% endblock %}

templates/users/user/register.html
{% extends "reviive/base.html" %}

{% load static %}

{% block page-title %}Register User{% endblock %}

{% block main %}

    <h2 id="section-heading">Register User</h2>

    <div class="extra-padding">

        <form id="register-username" action="{% url 'users:register' %}" method="post">
            <p>*required.</p>
<br>
            <label for="register-username">Username</label>
            <input id="register-username" name="username" type="text" required>

            <label for="register-email">Email*</label>
            <input id="register-email" name="email" type="email" required>

            <label for="register-password">Password*</label>
            <input id="register-password" name="password" type="password" required>
<br><br>
            <label for="register-first_name">first_name*</label>
            <input id="register-first_name" name="first_name" type="first_name" required>

            <label for="register-last_name">last_name*</label>
            <input id="register-last_name" name="last_name" type="last_name" required>

            <input type="submit" name="submit" value="Register">
            {% csrf_token %}

        </form>

    </div>

{% endblock %}

{% block css %}{% static "css/register.css" %}{% endblock %}